<script>
	import { Accordion, AccordionItem } from '@skeletonlabs/skeleton';
</script>

<div class="p-4">
	<div class="card p-8">
		The <strong> PACTA (Paris Agreement Capital Transition Assessment) </strong> dashboard provides
		a comprehensive view of your organization's alignment with climate transition goals. It enables
		you to assess the climate-related risks and opportunities within your investments, offering
		insights into how well your portfolio is positioned to align with multiple climate objectives.
		This section provides a high-level overview of the dashboard's functionalities, setting the
		stage for in-depth analysis across various levels—from portfolio-wide metrics to
		company-specific evaluations. Key features in this section:
		<ul class="list-disc p-4">
			<li><strong>Overview of the methodology</strong> behind the PACTA analysis;</li>
			<li><strong>Sector and asset class</strong> coverage in the analysis;</li>
			<li>
				<strong>Metrics used to assess alignment with climate targets </strong> (e.g., emission intensity,
				future technology)
			</li>
		</ul>
		To explore more detailed content for each section below, simply click on the titles. A dropdown will
		appear with further explanations and insights for each topic. This allows you to dig deeper into
		the information that matters most to you.
	</div>
</div>
<div class="p-4">
	<div class="card p-8">
		<Accordion autocollapse>
			<AccordionItem>
				<svelte:fragment slot="lead">
					<i class="fa-solid fa-book-open"></i>
				</svelte:fragment>
				<svelte:fragment slot="summary"><h3 class="h3">About PACTA</h3></svelte:fragment>
				<svelte:fragment slot="content">
					<div class="p-4">
						PACTA (Paris Agreement Capital Transition Assessment) is a comprehensive tool designed
						to help investors assess the alignment of their portfolios with global climate goals. By
						evaluating how investee companies are positioned relative to different climate
						scenarios, PACTA provides portfolio insights into the potential risks and opportunities
						of transitioning to a low-carbon economy. PACTA uses climate scenario analysis to assess
						the exposure of portfolios to carbon-intensive sectors and technologies, helping
						investors understand how well their holdings align with pathways to limit global warming
						to well below 2°C, with an aspirational target of 1.5°C. The tool evaluates various
						asset classes, including listed equities and corporate bonds, and applies
						sector-specific metrics to assess the emissions intensity and transition progress of
						companies.
						<br /><br />
						The results generated by PACTA allow users to get a granular view of the exposure and climate
						goal alignment of their portfolios by sector and for related technologies. This information
						can be used to:
						<ul class="list-disc p-4">
							<li>help steer investment decisions in line with climate scenarios;</li>
							<li>inform decisions in relation to climate target-setting;</li>
							<li>
								gain insights that can support engagement with clients on their respective climate
								actions;
							</li>
							<li>
								identify exposure to transition risks associated with a shift to a low-carbon
								economy.
							</li>
						</ul>
					</div>
				</svelte:fragment>
			</AccordionItem>
			<AccordionItem>
				<svelte:fragment slot="lead"><i class="fa-solid fa-industry"></i></svelte:fragment>
				<svelte:fragment slot="summary">
					<h3 class="h3">
						Economic Sectors Covered in PACTA and Their Relevance for Limiting Climate Change
					</h3>
				</svelte:fragment>
				<svelte:fragment slot="content">
					<div class="p-4">
						Climate change is no longer a distant threat; its physical impacts are already being
						felt across the globe. To avoid significant disruptions and economic losses, businesses
						must transform their operations, adapt their value chains, and implement sustainable
						practices. At the same time, economy-wide action is critical to mitigate and adapt to
						the accelerating impacts of climate change, particularly through investments aimed at
						reducing CO2 emissions across key sectors. These efforts are essential to prevent global
						temperatures from rising to dangerous levels.
						<br /><br />
						According to Our World In Data, taking a closer look at global greenhouse gas (GHG) emissions
						reveals where urgent action is required. Approximately 73% of global emissions stem from
						the energy sector (including electricity, heat, and transport), 18.4% from agriculture, forestry,
						and land use, 5.2% from direct industrial processes (such as cement, chemicals, and petrochemicals),
						and 3.2% from waste management. These sectors are not only responsible for the majority of
						emissions but are also critical areas where investment in low-carbon technologies can have
						the greatest impact.
						<br /><br />
						PACTA (Paris Agreement Capital Transition Assessment) focuses on seven of the most carbon-intensive
						sectors, which are likely to face significant transition risks as the world shifts toward
						a low-carbon economy. These sectors include Oil & Gas, Coal, Power, Automotive, Steel, Cement,
						and Aviation. Within each sector, PACTA examines the areas of the value chain that contribute
						most significantly to CO2 emissions and where the potential for emission reductions is most
						significant.
						<br /><br />
						PACTA's methodology targets the technology transitions needed within these sectors according
						to climate change scenarios, emphasizing the phase-out of high-carbon technologies and the
						ramp-up of low-carbon solutions. For example, in the Oil & Gas sector, the focus is on upstream
						production activities, while in the Power sector, it is centered on power generation capacity
						and the energy sources used.
						<br /><br />
						By assessing these key areas, PACTA helps investors understand the alignment of their portfolios
						with the global shift towards a low-carbon future, highlighting where climate risks and opportunities
						lie across different sectors and value chains.
						<br />
						For more detailed information on the specific parts of each value chain that PACTA focuses
						on, see the diagram in the figure below:
						<br /><br />
						<div class="card p-4 bg-tertiary-200">
							<div class="flex justify-center">
								<img
									src="pacta_value_chain.svg"
									alt="PACTA Value Chain"
									style="height: 100%; width: auto;"
								/>
							</div>
							<p class="p-2">
								<i
									>Figure 1: PACTA Sectors for listed equity and corporate bonds. Supply chain
									segments with the largest contribution to climate change are colored blue.</i
								>
							</p>
						</div>
						<br />
						Because PACTA covers sectors with very different value chains, the scope of the emissions
						addressed by the analysis also varies between sectors. As an orientation, the Greenhouse
						Gas Protocol defines and categorizes emissions into scopes 1, 2, and 3. This widely used
						corporate standard aims to support companies in understanding their full value chain emissions.
						According to the Greenhouse Gas Protocol, the scopes are defined as follows:
						<ul class="list-disc p-4">
							<li>
								Scope 1: GHG emissions occurring from sources that are owned or controlled by the
								company, for example, emissions from combustion in owned or controlled boilers,
								furnaces, vehicles, etc.; emissions from chemical production in owned or controlled
								process equipment;
							</li>
							<li>
								Scope 2: GHG emissions from the generation of purchased electricity consumed by the
								company;
							</li>
							<li>
								Scope 3: GHG emissions resulting as a consequence of the activities of the company
								but that occur from sources not owned or controlled by the company. Some examples of
								scope 3 activities are extraction and production of purchased materials;
								transportation of purchased fuels; and use of sold products and services.
							</li>
						</ul>
						PACTA measures alignment with scenarios using a combination of production capacity and CO₂
						emissions intensity metrics. The analysis covers scope 1 for aviation and power, scopes 1
						and 2 for steel and cement, scope 3 for automotive and coal, and scope 1,2 and 3 for oil
						and gas. However, we strongly recommend the use of the production capacity metrics to inform
						decision-making rather than GHG emissions for the power, automotive, coal, and oil and gas
						sectors since they provide technology-level insights on what needs to happen according to
						the scenario pathways.
					</div>
				</svelte:fragment>
			</AccordionItem>
			<AccordionItem>
				<svelte:fragment slot="lead"><i class="fa-solid fa-magnifying-glass"></i></svelte:fragment>
				<svelte:fragment slot="summary"
					><h3 class="h3">The PACTA Methodology at a Glance</h3>
				</svelte:fragment>
				<svelte:fragment slot="content">
					<div class="p-4">
						The PACTA methodology compares the sectoral decarbonization pathways—developed by
						leading climate scenario providers—with the financial exposure of investors to companies
						in high-carbon sectors such as oil and gas, coal, power, automotive, cement, aviation,
						and steel (referred to as the "PACTA sectors"). The analysis provides a five-year
						forward-looking, bottom-up assessment, focusing primarily on the necessary technology
						transitions within these sectors.
						<br /><br />
						The PACTA analysis highlights the need to phase out high-emitting technologies and scale
						up low-carbon alternatives. It uses climate scenarios to quantify the required technology
						shifts and sectoral decarbonization needed to meet the Paris Agreement goals: limiting global
						warming to well below 2°C and striving for 1.5°C, as well as other, less ambitious climate
						targets.
						<br /><br />
						The climate scenario analysis for listed equities and corporate bonds, based on the PACTA
						methodology, provides actionable insights by answering critical questions about portfolio
						alignment with climate goals:
						<ul class="list-disc p-4">
							<li>
								Exposure to high emitting sectors: What proportion of the portfolio is invested in
								high-carbon sectors?
							</li>
							<li>
								Emissions Relevance: How significant is the carbon intensity of the analyzed portion
								of the portfolio in terms of overall emissions?
							</li>
							<li>
								Scenario Alignment: Which climate change scenarios do the production plans of
								companies in the portfolio align with?
							</li>
							<li>
								Key Impactful Companies: Which companies in the portfolio are driving the results
								and influencing the overall alignment?
							</li>
							<li>
								Benchmark Comparison: How does the portfolio perform relative to market benchmarks?
							</li>
						</ul>
						PACTA analyzes companies' five-year forward-looking production plans based on physical asset-level
						data, assessing how aligned these plans are with various climate scenarios. This company-specific
						data is then consolidated to provide portfolio-level results, offering a clear view of misalignment
						or alignment with transition pathways.
						<br /><br />
						The results help investors understand potential exposure to both transition risks and opportunities.
						This forward-looking approach provides valuable insights for:
						<ul class="list-disc p-4">
							<li>Transition Risk Management</li>
							<li>Engagement with Companies on climate strategies</li>
							<li>Disclosure and Reporting on climate alignment</li>
							<li>Strategic Decision-Making</li>
						</ul>
						The following table provides an overview of key components and principles underlying the
						PACTA methodology.
						<br /><br />
						<!-- Responsive Container (recommended) -->
						<div class="table-container">
							<!-- Native Table Element -->
							<table class="table table-hover bg-surface-200 p-4">
								<tbody>
									<tr>
										<td><strong>Physical asset-based company level data (ABCD)</strong></td>
										<td>
											The analysis is currently based on data covering 52,000+ companies and
											230,000+ energy-related physical assets from third-party data providers. This
											alleviates the necessity to rely on companies’ self-reported data that is
											published in a non-standardized manner and often does not account for scope 2
											and 3 emissions.
										</td>
									</tr>
									<tr>
										<td><strong>Forward-Looking</strong></td>
										<td>
											PACTA provides a five-year forward-looking analysis of the production plans
											financed by a portfolio that are compared to climate scenarios.
										</td>
									</tr>
									<tr>
										<td><strong>Sector-specific approach</strong></td>
										<td>
											The outputs of the analysis are metrics and indicators at sector and
											technology-level that allow for a detailed evaluation of a portfolio’s
											alignment, rather than one aggregated indicator at portfolio level.
										</td>
									</tr>
									<tr>
										<td><strong>Allocating macroeconomic goals to microeconomic actors</strong></td>
										<td>
											The PACTA analysis uses a market-share approach to allocate macroeconomic
											climate targets to companies in sectors where low-carbon technologies are
											available thus, all market-level trends and targets are allocated to companies
											based on their current market share in the sector or technology for low- and
											high-carbon technologies, respectively.
										</td>
									</tr>
								</tbody>
							</table>
						</div>
						<br />
						In the analysis provided for each sector, the user has the option to select from two different
						portfolio attribution methodologies - the Portfolio Weight Approach (PA) and the Ownership
						Weight Approach (OA). These methods are used to attribute the physical assets of a company
						to the financial instrument or portfolio.
						<br />
						The approaches differ as follows:
						<ul class="list-disc p-4">
							<li>
								Portfolio Weight Approach (PA): This approach calculates the portfolios’ technology
								exposures based on the weighting of each position within the portfolio. Therefore,
								the PA reflects the investor´s allocation choice. This approach is used for the
								analysis of corporate bonds and can be used for listed equity as well.
							</li>
							<li>
								Ownership Weight Approach (OA): This approach assigns a share of the companies’
								activities to the portfolio based on the percent of outstanding shares owned by the
								investor. This approach comes closer to allocating “responsibility” for the
								companies’ activities to the financial institution.
							</li>
							While the Ownership Weight Approach (OA) is only available for listed equity, the Portfolio
							Weight Approach (PA) is available for both corporate bonds and listed equity.
						</ul>
						While the Ownership Weight Approach (OA) is only available for listed equity, the Portfolio
						Weight Approach (PA) is available for both corporate bonds and listed equity.
					</div>
				</svelte:fragment>
			</AccordionItem>
			<AccordionItem>
				<svelte:fragment slot="lead"><i class="fa-solid fa-trowel-bricks"></i></svelte:fragment>
				<svelte:fragment slot="summary">
					<h3 class="h3">Inputs into the PACTA Methodology</h3>
				</svelte:fragment>
				<svelte:fragment slot="content">
					<div>
						This section covers the core concepts of the methodology, allowing a reader to correctly
						interpret the results being presented in the PACTA analysis. Some of the key assumptions
						and limitations are also highlighted at the end of this chapter. This is not intended to
						be a detailed description of the methodology; for more information about the
						methodology, please refer to the knowledge hub on the Transition Monitor website, or to
						the PACTA for Investors methodology document, also available on the Transition Monitor
						website.
						<br /><br />
						<h4 class="h4">Data and Scenarios</h4>
						<h5 class="h5">Asset-Based Company-Level Data</h5>
						<br />
						The PACTA methodology measures the alignment of a financial portfolio to decarbonization
						pathways set out in climate change scenarios. It does this by attributing physical assets
						in the real economy to the financial assets that finance them. The physical asset-based company-level
						data used for this analysis is provided by Asset Impact.
						<br /><br />
						The production values of each company in the dataset provided by Asset Impact, measured as
						an economic unit of output, are known. For example, the number of cars produced or barrels
						of oil for automotive and oil assets, respectively. The asset’s production values are allocated
						to the companies owning them based on the “Credit Ownership” and the “Equity Ownership” consolidation
						methodologies. For more information related to the consolidation of physical assets to companies
						please refer to the PACTA for Investors methodology document.
						<br /><br />
						<h5 class="h5">Scenarios</h5>
						Climate change scenarios are an important tool to explore and understand what can happen
						and what may need to happen in the future under different conditions and in order to achieve
						certain outcomes. Scenarios are only depictions and models of the future and so do not predict
						what will happen with 100% certainty in the upcoming years. Instead they propose different
						views of the future, under different political, economic and social contexts and with different
						possible decarbonization outcomes.
						<br /><br />
						The PACTA Methodology is intended to be agnostic and to be able to use any climate scenario
						that lays out production capacity targets at the technology level or, for the relevant sectors,
						emission-intensity units. Scenarios typically differ in the following main ways:
						<br />
						<ul class="list-disc p-4">
							<li>
								They implement decarbonization pathways of different levels of ambition and
								probability;
							</li>
							<li>
								They lay out decarbonization pathways that occur at different speeds (rapid ramp-up
								or long-term adjustment);
							</li>
							<li>
								They make different assumptions around innovation and, thus, around technologies’
								availability, scalability, and costs;
							</li>
							<li>
								They offer varying levels of granularity, e.g., they may cover different time
								horizons and geographic scales.
							</li>
						</ul>
						Given that the targets laid out in climate scenarios can vary by region depending on the
						sector’s value chain and geographic constraints (e.g., power distribution), alignment is
						measured at the geographical level in which the sector tends to operate and seek investment.
						For example, for the power sector, markets tend to be regional or national, and as such,
						alignment should be measured at that level. However, the oil, gas, coal and automotive sectors
						operate in a global market and in such a case a global scenario target is used.
						<br /><br />
						Not all scenarios provide information for all sectors analyzed in the PACTA assessment, therefore
						different sectors might be analyzed using different scenarios. However, in general we recommend
						using the same scenario where possible when performing the portfolio analysis, since the
						sectoral pathways within scenarios are created to meet the same overall carbon budget.
						<br /><br />
						We further recommend that investors seek to understand the scenarios used, and their underlying
						assumptions, in order to evaluate which of them is more appropriate for their purposes. For
						further information on the scenarios included in this analysis, please refer to the scenario
						document available on the Transition Monitor website.
						<br /><br />
						<h4 class="h4">Time horizons</h4>
						Results given in this analysis are shown for the present and up to 5 years in the future.
						This is based on the capital expenditure (CAPEX) plans reported by the company’s current
						asset-based company data (ABCD). For some sectors, a reliable estimate beyond 5 years cannot
						be made due to the lack of adequate data forecasts beyond that time frame. In PACTA, for
						the sake of homogeneity and consistency, we provide the forecast information on a 5 year
						forward looking basis.
						<br /><br />
						<h5 class="h5">Data Sources</h5>
						<ul class="list-disc p-4">
							<li>
								© 2023 Asset Impact. All Rights Reserved. Information, data, analyses and opinions
								contained herein: (1) include the proprietary information of Asset Impact and its
								content providers; (2) may not be copied or redistributed except as specifically
								authorised in writing; (3) do not constitute investment advice; (4) are provided
								solely for informational purposes; (5) are not warranted to be complete, accurate or
								timely; and (6) may be drawn from data published on various dates. Asset Impact is
								not responsible for any decisions, damages or other losses related to the
								information, data, analyses or opinions contained herein or the use thereof. Please
								verify all of the information before using it and do not make any investment
								decision except upon the advice of a professional financial adviser. Past
								performance is not a guarantee of future results. The value and income derived from
								investments may go down and up.
							</li>
							<li>
								FactSet (Copyright © 2023 FactSet Research Systems Inc. All rights reserved.)
							</li>
							<li>
								ETP2020: IEA (2020), Energy Technology Perspectives 2020, IEA, Paris
								https://www.iea.org/reports/energy-technology-perspectives-2020, License: CC BY 4.0
							</li>
							<li>
								GECO2022 : Keramidas, K., Fosse, F., Diaz Rincon, A., Dowling, P., Garaffa, R.,
								Ordonez, J., Russ, P., Schade, B., Schmitz, A., Soria Ramirez, A., Vandyck, T. and
								Weitzel, M., Global Energy and Climate Outlook 2022: Energy trade in a decarbonised
								world, EUR 31355 EN, Publications Office of the European Union, Luxembourg, 2022,
								ISBN 978-92-76-60498-3, doi:10.2760
							</li>
						</ul>
					</div>
				</svelte:fragment>
			</AccordionItem>
			<AccordionItem>
				<svelte:fragment slot="lead"><i class="fa-solid fa-chart-area"></i></svelte:fragment>
				<svelte:fragment slot="summary">
					<h3 class="h3">PACTA Core Metrics overview</h3>
				</svelte:fragment>
				<svelte:fragment slot="content">
					The PACTA analysis evaluates portfolio alignment with climate transition goals using three
					key metrics, two of which are based on production capacity. These metrics help measure how
					well a portfolio is positioned for the transition to a low-carbon economy:
					<br />
					<ol class="list-decimal p-4">
						<li>Technology Share Mix</li>
						<li>Production Volume Trajectory</li>
						<li>Emission Intensity</li>
					</ol>
					The first two metrics (Technology Share Mix and Production Volume Trajectory) are used for
					sectors with clear technology transition pathways, as defined by the climate change scenarios,
					such as power, fossil fuels, and automotive. The emission intensity metric is used for sectors
					where technology transitions are less defined—such as steel, cement, and aviation. Below, each
					metric is explained in more detail.
					<br />
					<h4 class="h4">Technology Share Mix</h4>
					The Technology Share Mix metric measures the proportion of each technology within a sector
					as a percentage of the portfolio investment in the portfolio-level overview tab, and as a percentage
					of the sectoral production in the sector-level analysis tab. It reflects the mix of technologies
					being used in the sector, which can indicate how exposed the portfolio is to sectors undergoing
					a transition to low-carbon alternatives.
					<br /><br />
					For example, in the power sector, this metric tracks the proportion of production coming from
					renewable energy compared to coal-fired generation. Similarly, in the automotive sector, it
					shows the share of production coming from electric vehicles versus traditional internal combustion
					engine vehicles.
					<br /><br />
					The Technology Share Mix gives more insight into the relative exposure to different technologies,
					especially when compared with the volume trajectory, and provides a clearer picture of how
					a company's production is distributed across different technological solutions.
					<br /><br />
					When comparing current and future tech mix for a specific sector along with the volume trajectory
					results, the Technology Share Mix gives insights on two key types of changes:
					<br />

					<ul class="list-disc p-4">
						<li>
							Process Changes: Shifts in the technology or processes used to produce outputs (e.g.,
							transitioning from coal to renewable power generation).
						</li>
						<li>
							Output Changes: Shifts in the products themselves (e.g., transitioning from internal
							combustion engine vehicles to electric vehicles)
						</li>
					</ul>
					<h4 class="h4">Production Volume Trajectory</h4>
					The Production Volume Trajectory metric measures how a portfolio’s projected production volumes
					align with climate transition goals. This metric compares companies' five-year capital commitments
					for production to their target production volume trajectories under different climate scenarios.
					It applies to sectors with clear technology pathways, such as oil and gas, coal, automotive,
					and power. This metric focuses on the volume of production, capturing whether companies are
					increasing or decreasing production volumes over time and how that aligns with climate targets.
					For instance, it could track whether a company is scaling back coal production or increasing
					the output of electric vehicles.
					<br /><br />
					Changes in production volumes can result from:
					<ul class="list-disc p-4">
						<li>
							Technology Shifts: The transfer of production from one technology to another (e.g.,
							moving from internal combustion engines to electric vehicles).
						</li>
						<li>
							Production Adjustments: Changes in the overall scale of production for a given
							technology or fuel (e.g., expanding or contracting coal-fired power generation)
						</li>
					</ul>
					<h4 class="h4">Emission Intensity</h4>
					The Emission Intensity metric measures the carbon intensity of production in sectors where
					clear technology pathways are not yet established, such as steel, cement, and aviation. It
					calculates the CO₂ emissions per unit of output (e.g., CO₂ per ton of steel produced) and compares
					that to the reduction trajectory for emissions intensity set out by a climate scenario for
					the sector. In these sectors, no clear zero-carbon alternatives currently exist, so the Technology
					Share Mix and Production Volume Trajectory metrics are not applicable. However, emissions must
					still be reduced significantly to align with climate goals. The Emission Intensity metric helps
					guide capital allocation toward reducing carbon emissions in these sectors in line with the
					required reduction trajectories, even without clear technology shifts
					<br /><br />
					Each of the three PACTA metrics provides unique insights into how a portfolio aligns with climate
					transition goals. The Technology Share Mix focuses on the distribution of production by technology
					within sectors, offering a current and five-year forward-looking snapshot of relative exposure
					to low- and high-carbon technologies. The Production Volume Trajectory looks at projected production
					volumes and their alignment with climate scenarios, while the Emission Intensity metric addresses
					the carbon intensity of sectors without defined technological pathways. Together, these metrics
					provide a comprehensive view of the portfolio’s alignment with climate transition goals.
					<br />
				</svelte:fragment>
			</AccordionItem>
			<AccordionItem>
				<svelte:fragment slot="lead"><i class="fa-solid fa-building-columns"></i></svelte:fragment>
				<svelte:fragment slot="summary"
					><h3 class="h3">Disclaimers and Limitations of the Analysis</h3></svelte:fragment
				>
				<svelte:fragment slot="content">
					<ol class="list-decimal p-4">
						<li>
							Data uploaded from financial institutions: The interactive results provided in this
							analysis depend on the data uploaded by the user. RMI is not responsible for any
							validation or audit of the uploaded data.
						</li>
						<li>
							Climate scenario assumptions: The climate scenarios used present one possible
							manifestation of how the energy transition aligned with different climate targets
							could look like. Even though the necessary actions are not controversial (expansion of
							renewables, retirement of high-carbon technologies), the precise way in which a
							remaining carbon budget is distributed across sectors can be achieved in different
							ways according to different scenarios. Furthermore, different models will include
							different assumptions about the future development and potential of certain
							technologies. This analysis therefore focuses on those technologies that are proven
							and available to the market. As a result, this analysis does not consider investments
							in R&D or private equity, which represent an important way for financial institutions
							to help bring new solutions to the market. Additionally, while scenarios are expected
							to incorporate all socioeconomic considerations, they don’t take into account
							regionally specific policies or regulations. For this reason, it is expected that in
							some technologies alignment may be more difficult or even unfeasible.
						</li>
						<li>
							Asset based company level data used: Although the data is sourced from reliable,
							third-party data providers, errors are possible, either in the production plans
							themselves, or in mapping the ownership structure of a company. Furthermore, planned
							production plans do not necessarily materialize, and production forecasts should be
							interpreted bearing this in mind.
						</li>
						<li>
							Current fund coverage in the PACTA analysis: Whenever institutions report funds in
							their portfolios they are converted into equities and bonds assigned to that fund
							ISIN. To complete this conversion, we rely on external data sources containing
							information on funds and their compositions.
						</li>
						<li>
							Scope of the analysis: PACTA does not cover certain sectors, such as agriculture and
							forestry, even though they are highly relevant for limiting future GHG emissions, due
							to a lack of available data. Furthermore, asset classes such as sovereign bonds or
							private equity are also not included in the analysis.
						</li>
						<li>
							Companies’ plans: Companies’ relative extents of climate alignment are approximated
							using production capacity-based figures, and do not encapsulate R&D investment,
							historical record, lobbying expenditures, etc.
						</li>
						<li>
							Sector classification: PACTA maps asset-based company-level data to financial assets
							considering sector classification provided by our financial data provider. While RMI
							performs quality assurance of data included in the analysis, some companies might
							still be wrongly classified.
						</li>
					</ol>
				</svelte:fragment>
			</AccordionItem>
			<!-- ... -->
		</Accordion>
	</div>
</div>
